import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const notoSansJp = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-noto-sans-jp',
});

export const metadata: Metadata = {
  title: {
    template: '%s | MyKuji.JP',
    default: 'MyKuji.JP', // a default is required when creating a template
  },
  description: "Generated by mykuji.jp",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        notoSansJp.className
      )}>
        {children}
      </body>
    </html>
  );
}
